### ISSUE TITLE
faliure to serialize user into the session

### ISSUE THREAD

**Issue by giorgioGTelian** [giorgioGTelian/Mern_dashboard#13]
`
Error: Failed to serialize user into session
    at pass (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport\lib\authenticator.js:278:19)
    at serialized (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport\lib\authenticator.js:283:7)
    at file:///C:/Users/giorgio/PersonalProjects/Mern_dashboard/server/index.js:130:5
    at pass (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport\lib\authenticator.js:291:9)
    at Authenticator.serializeUser (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport\lib\authenticator.js:296:5)
    at SessionManager.logIn (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport\lib\sessionmanager.js:14:8)
    at req.login.req.logIn (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport\lib\http\request.js:39:26)
    at strategy.success (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport\lib\middleware\authenticate.js:256:13)
    at verified (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\passport-oauth2\lib\strategy.js:189:20)
    at Strategy._verify (file:///C:/Users/giorgio/PersonalProjects/Mern_dashboard/server/index.js:120:2
`

**Comment by giorgioGTelian** [comment]
resolved with refractor of code
