### ISSUE TITLE
validation schema error

### ISSUE THREAD

**Issue by giorgioGTelian** [giorgioGTelian/Mern_dashboard#4]
from starting npm start dev
```bash
C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongoose\lib\document.js:3289
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: User validation failed: id: Path `id` is required.
    at Document.invalidate (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongoose\lib\document.js:3289:32)
    at C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongoose\lib\document.js:3050:17
    at C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongoose\lib\schemaType.js:1388:9
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  errors: {
    id: ValidatorError: Path `id` is required.
        at validate (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongoose\lib\schemaType.js:1385:13)
        at SchemaType.doValidate (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongoose\lib\schemaType.js:1369:7)
        at C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongoose\lib\document.js:3042:18
        at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
      properties: {
        validator: [Function (anonymous)],
        message: 'Path `id` is required.',
        type: 'required',
        path: 'id',
        fullPath: undefined,
        value: undefined
      },
      kind: 'required',
      path: 'id',
      value: undefined,
      reason: undefined,
      [Symbol(mongoose#validatorError)]: true
    }
  },
  _message: 'User validation failed'
}

Node.js v21.6.1
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by giorgioGTelian** [comment]
in model/User.js i deleted id required since before making the call it must be declare
```javascript
//schema that defines the structure of the user data
import mongoose from 'mongoose';
//TODO add more fields to the user schema - also id
const UserSchema = new mongoose.Schema({
    name: {
        type: String,
        required: true,
        min: 3,
        max: 100,
    },
    email: {
        type: String,
        required: true,
        min: 3,
        max: 100,
    },
    password: {
        type: String,
        required: true,
        min: 6,
        max: 100,
    },
    id: {
        type: String,
    }, 
    city: String,
    state: String,
```
