### ISSUE TITLE
node id validation error

### ISSUE THREAD

**Issue by giorgioGTelian** [giorgioGTelian/Mern_dashboard#5]
```node
C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongodb\lib\bulk\common.js:825
            callback(new MongoBulkWriteError({
                     ^

MongoBulkWriteError: E11000 duplicate key error collection: test.users index: _id_ dup key: { _id: ObjectId('63701cc1f03239c72c000180') }
    at OrderedBulkOperation.handleWriteError (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongodb\lib\bulk\common.js:825:22)
    at resultHandler (C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongodb\lib\bulk\common.js:303:27)
    at C:\Users\giorgio\PersonalProjects\Mern_dashboard\server\node_modules\mongodb\lib\bulk\common.js:345:116
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errorResponse: {
    message: "E11000 duplicate key error collection: test.users index: _id_ dup key: { _id: ObjectId('63701cc1f03239c72c000180') }",
    code: 11000,
    writeErrors: [
      {
        err: {
          index: 0,
          code: 11000,
          errmsg: "E11000 duplicate key error collection: test.users index: _id_ dup key: { _id: ObjectId('63701cc1f03239c72c000180') }",
          errInfo: undefined,
          op: {
            name: 'Marilyn',
            email: 'mdonlon1@hostgator.com',
            password: 'XRYBnKAfm',
            city: 'Zhanghekou',
            state: null,
            country: 'CN',
            occupation: 'Food Chemist',
            phoneNumber: '9981906117',
            transactions: [Array],
            role: 'user',
            _id: [ObjectId],
            __v: 0,
            createdAt: 2024-05-16T08:59:42.133Z,
            updatedAt: 2024-05-16T08:59:42.133Z
          }
        },
        index: 0
      }
    ]
  },
  code: 11000,
  writeErrors: [
    {
      err: {
        index: 0,
        code: 11000,
        errmsg: "E11000 duplicate key error collection: test.users index: _id_ dup key: { _id: ObjectId('63701cc1f03239c72c000180') }",
        errInfo: undefined,
        op: {
          name: 'Marilyn',
          email: 'mdonlon1@hostgator.com',
          password: 'XRYBnKAfm',
          city: 'Zhanghekou',
          state: null,
          country: 'CN',
          occupation: 'Food Chemist',
          phoneNumber: '9981906117',
          transactions: [
            '63701d74f03239b7f7000027',
            '63701d74f03239db69000153',
            '63701d74f03239569400002d',
            '63701d74f032394c4900014b'
          ],
          role: 'user',
          _id: ObjectId { buffer: [Buffer [Uint8Array]] },
          __v: 0,
          createdAt: 2024-05-16T08:59:42.133Z,
          updatedAt: 2024-05-16T08:59:42.133Z
        }
      },
      index: 0
    }
  ],
  result: BulkWriteResult {
    insertedCount: 0,
    matchedCount: 0,
    modifiedCount: 0,
    deletedCount: 0,
    upsertedCount: 0,
    upsertedIds: {},
    insertedIds: {}
  },
  insertedDocs: [],
  [Symbol(errorLabels)]: Set(0) {}
}

Node.js v21.6.1
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by giorgioGTelian** [comment]
the initial 
```javascript
User.insertMany(dataUser); DONE
```
inside mongoose invocation is just for the first time
